sudo: required
services:
  - docker

before_install:
  - docker build -t clavance/fib -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true clavance/fib npm test

after_success:
  - docker build -t clavance/fib-client ./client
  - docker build -t clavance/fib-nginx ./nginx
  - docker build -t clavance/fib-server ./server
  - docker build -t clavance/fib-worker ./worker
  # log in to docker (set env variables in Travis CI)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push clavance/fib-client
  - docker push clavance/fib-nginx
  - docker push clavance/fib-server
  - docker push clavance/fib-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: fibonacci
  env: Fibonacci-env
  bucket_name: elasticbeanstalk-us-east-2-306534435678
  bucket_path: fibonacci
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
